<?php

namespace Database\Seeders;

use App\Models\Glossary;
use Illuminate\Database\Seeder;

class GlossarySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $glossaries = [
            // Letter A
            [
                'term_en' => 'A/B testing',
                'term_fr' => 'Test A/B',
                'definition_en' => 'A method of comparing two versions of a webpage, email, or feature to determine which performs better based on user behavior.',
                'definition_fr' => 'Une méthode de comparaison de deux versions d\'une page web, d\'un email ou d\'une fonctionnalité pour déterminer laquelle performe le mieux selon le comportement des utilisateurs.',
                'letter' => 'A',
                'order' => 1,
            ],
            [
                'term_en' => 'Acquisition cost (CAC)',
                'term_fr' => 'Coût d\'acquisition client (CAC)',
                'definition_en' => 'Customer Acquisition Cost is the total expense required to acquire a new customer, including marketing, sales, and advertising costs.',
                'definition_fr' => 'Le coût d\'acquisition client est la dépense totale nécessaire pour acquérir un nouveau client, incluant les coûts de marketing, de vente et de publicité.',
                'letter' => 'A',
                'order' => 2,
            ],
            [
                'term_en' => 'Agile development',
                'term_fr' => 'Développement Agile',
                'definition_en' => 'An iterative approach to software development that promotes collaboration, adaptability, and continuous delivery.',
                'definition_fr' => 'Une approche itérative du développement logiciel qui favorise la collaboration, l\'adaptabilité et la livraison continue.',
                'letter' => 'A',
                'order' => 3,
            ],
            [
                'term_en' => 'API (Application Programming Interface)',
                'term_fr' => 'API (Interface de programmation d\'application)',
                'definition_en' => 'A set of protocols and tools that allow different software applications to communicate and share data.',
                'definition_fr' => 'Un ensemble de protocoles et d\'outils permettant à différentes applications logicielles de communiquer et de partager des données.',
                'letter' => 'A',
                'order' => 4,
            ],

            // Letter B
            [
                'term_en' => 'Backlog',
                'term_fr' => 'Backlog',
                'definition_en' => 'A prioritized list of tasks, features, or bugs waiting to be developed or addressed in future sprints.',
                'definition_fr' => 'Une liste priorisée de tâches, fonctionnalités ou bugs en attente de développement ou de traitement dans les sprints futurs.',
                'letter' => 'B',
                'order' => 1,
            ],
            [
                'term_en' => 'Beta release',
                'term_fr' => 'Version bêta',
                'definition_en' => 'A pre-launch version of a software product released to selected users for testing and feedback.',
                'definition_fr' => 'Une version pré-lancement d\'un produit logiciel distribuée à des utilisateurs sélectionnés pour des tests et retours.',
                'letter' => 'B',
                'order' => 2,
            ],
            [
                'term_en' => 'Bootstrapping',
                'term_fr' => 'Autofinancement',
                'definition_en' => 'Building and growing a company using personal savings or internal revenue rather than external funding.',
                'definition_fr' => 'Construire et développer une entreprise en utilisant des économies personnelles ou des revenus internes plutôt que des financements externes.',
                'letter' => 'B',
                'order' => 3,
            ],

            // Letter C
            [
                'term_en' => 'Churn Rate',
                'term_fr' => 'Taux d\'attrition',
                'definition_en' => 'The percentage of customers who cancel or stop using a subscription service during a given period.',
                'definition_fr' => 'Le pourcentage de clients qui annulent ou cessent d\'utiliser un service d\'abonnement pendant une période donnée.',
                'letter' => 'C',
                'order' => 1,
            ],
            [
                'term_en' => 'Cloud computing',
                'term_fr' => 'Informatique en nuage',
                'definition_en' => 'The delivery of computing services including servers, storage, databases, and software over the internet instead of local infrastructure.',
                'definition_fr' => 'La fourniture de services informatiques incluant serveurs, stockage, bases de données et logiciels via internet plutôt qu\'une infrastructure locale.',
                'letter' => 'C',
                'order' => 2,
            ],
            [
                'term_en' => 'Conversion rate',
                'term_fr' => 'Taux de conversion',
                'definition_en' => 'The percentage of users who complete a desired action (such as signing up, purchasing, or upgrading) out of the total number of visitors.',
                'definition_fr' => 'Le pourcentage d\'utilisateurs qui accomplissent une action souhaitée (comme s\'inscrire, acheter ou mettre à niveau) sur le nombre total de visiteurs.',
                'letter' => 'C',
                'order' => 3,
            ],
            [
                'term_en' => 'CRM (Customer Relationship Management)',
                'term_fr' => 'GRC (Gestion de la Relation Client)',
                'definition_en' => 'Software that helps businesses manage interactions with existing and potential customers to improve relationships and retention.',
                'definition_fr' => 'Logiciel qui aide les entreprises à gérer les interactions avec les clients existants et potentiels pour améliorer les relations et la fidélisation.',
                'letter' => 'C',
                'order' => 4,
            ],
            [
                'term_en' => 'Customer lifetime value (CLV or LTV)',
                'term_fr' => 'Valeur vie client (CLV ou LTV)',
                'definition_en' => 'The total revenue a business can expect from a customer over the entire duration of their relationship.',
                'definition_fr' => 'Le revenu total qu\'une entreprise peut attendre d\'un client sur toute la durée de leur relation.',
                'letter' => 'C',
                'order' => 5,
            ],

            // Letter D
            [
                'term_en' => 'Dashboard',
                'term_fr' => 'Tableau de bord',
                'definition_en' => 'A visual interface that displays key metrics, analytics, and performance indicators in real time for easy monitoring and decision-making.',
                'definition_fr' => 'Une interface visuelle qui affiche les métriques clés, les analyses et les indicateurs de performance en temps réel pour faciliter le suivi et la prise de décision.',
                'letter' => 'D',
                'order' => 1,
            ],
            [
                'term_en' => 'Data analytics',
                'term_fr' => 'Analyse de données',
                'definition_en' => 'The process of collecting, analyzing, and interpreting data to uncover patterns, trends, and insights that guide business decisions.',
                'definition_fr' => 'Le processus de collecte, d\'analyse et d\'interprétation des données pour découvrir des tendances, des modèles et des insights qui guident les décisions d\'affaires.',
                'letter' => 'D',
                'order' => 2,
            ],
            [
                'term_en' => 'Data migration',
                'term_fr' => 'Migration de données',
                'definition_en' => 'The process of transferring data from one system, platform, or storage type to another, often during upgrades or software transitions.',
                'definition_fr' => 'Le processus de transfert de données d\'un système, d\'une plateforme ou d\'un type de stockage à un autre, souvent lors de mises à niveau ou de transitions logicielles.',
                'letter' => 'D',
                'order' => 3,
            ],

            // Letter E
            [
                'term_en' => 'Engagement rate',
                'term_fr' => 'Taux d\'engagement',
                'definition_en' => 'A metric that measures how actively users interact with your product, content, or platform, often through clicks, time spent, or feature usage.',
                'definition_fr' => 'Une métrique qui mesure l\'interaction active des utilisateurs avec votre produit, contenu ou plateforme, souvent via les clics, le temps passé ou l\'utilisation des fonctionnalités.',
                'letter' => 'E',
                'order' => 1,
            ],
            [
                'term_en' => 'Enterprise SaaS',
                'term_fr' => 'SaaS Entreprise',
                'definition_en' => 'Software-as-a-Service designed for large organizations with advanced scalability, security, and customization needs.',
                'definition_fr' => 'Logiciel en tant que service conçu pour les grandes organisations avec des besoins avancés en évolutivité, sécurité et personnalisation.',
                'letter' => 'E',
                'order' => 2,
            ],
            [
                'term_en' => 'Error Log',
                'term_fr' => 'Journal d\'erreurs',
                'definition_en' => 'A record of issues, bugs, or failures that occur within a system, used by developers to diagnose and resolve problems.',
                'definition_fr' => 'Un enregistrement des problèmes, bugs ou échecs qui surviennent dans un système, utilisé par les développeurs pour diagnostiquer et résoudre les problèmes.',
                'letter' => 'E',
                'order' => 3,
            ],
            [
                'term_en' => 'ETL (Extract, Transform, Load)',
                'term_fr' => 'ETL (Extraire, Transformer, Charger)',
                'definition_en' => 'A process for collecting data from various sources, transforming it into a usable format, and loading it into a database or data warehouse.',
                'definition_fr' => 'Un processus de collecte de données depuis diverses sources, de transformation en format utilisable et de chargement dans une base de données ou un entrepôt de données.',
                'letter' => 'E',
                'order' => 4,
            ],
            [
                'term_en' => 'Event tracking',
                'term_fr' => 'Suivi des événements',
                'definition_en' => 'Monitoring specific user actions within a product (such as clicks or form submissions) to analyze behavior and optimize experiences.',
                'definition_fr' => 'Surveillance des actions spécifiques des utilisateurs dans un produit (comme les clics ou les soumissions de formulaires) pour analyser le comportement et optimiser les expériences.',
                'letter' => 'E',
                'order' => 5,
            ],
            [
                'term_en' => 'Evergreen content',
                'term_fr' => 'Contenu intemporel',
                'definition_en' => 'Content that remains relevant and valuable over time, often used in marketing and SEO strategies to attract long-term traffic.',
                'definition_fr' => 'Contenu qui reste pertinent et précieux dans le temps, souvent utilisé dans les stratégies marketing et SEO pour attirer du trafic à long terme.',
                'letter' => 'E',
                'order' => 6,
            ],

            // Letter F
            [
                'term_en' => 'Feature flag',
                'term_fr' => 'Indicateur de fonctionnalité',
                'definition_en' => 'A software switch that allows teams to enable, disable, or test features without deploying new code.',
                'definition_fr' => 'Un commutateur logiciel permettant aux équipes d\'activer, désactiver ou tester des fonctionnalités sans déployer de nouveau code.',
                'letter' => 'F',
                'order' => 1,
            ],
            [
                'term_en' => 'Funnel',
                'term_fr' => 'Entonnoir',
                'definition_en' => 'A marketing or sales model that illustrates the stages users go through before converting into paying customers.',
                'definition_fr' => 'Un modèle marketing ou commercial qui illustre les étapes par lesquelles passent les utilisateurs avant de devenir des clients payants.',
                'letter' => 'F',
                'order' => 2,
            ],
            [
                'term_en' => 'Freemium model',
                'term_fr' => 'Modèle freemium',
                'definition_en' => 'A business model offering a basic product for free while charging for premium features or advanced functionality.',
                'definition_fr' => 'Un modèle commercial offrant un produit de base gratuit tout en facturant les fonctionnalités premium ou avancées.',
                'letter' => 'F',
                'order' => 3,
            ],
            [
                'term_en' => 'Full stack developer',
                'term_fr' => 'Développeur full stack',
                'definition_en' => 'An engineer skilled in both front-end and back-end technologies, capable of building complete web applications.',
                'definition_fr' => 'Un ingénieur compétent en technologies front-end et back-end, capable de construire des applications web complètes.',
                'letter' => 'F',
                'order' => 4,
            ],
            [
                'term_en' => 'Functional requirements',
                'term_fr' => 'Exigences fonctionnelles',
                'definition_en' => 'Specific behaviors or functions a system must perform, defining how software should operate from the user\'s perspective.',
                'definition_fr' => 'Comportements ou fonctions spécifiques qu\'un système doit accomplir, définissant comment le logiciel doit fonctionner du point de vue de l\'utilisateur.',
                'letter' => 'F',
                'order' => 5,
            ],
            [
                'term_en' => 'Feedback loop',
                'term_fr' => 'Boucle de rétroaction',
                'definition_en' => 'A process of gathering user feedback, analyzing it, and applying insights to improve the product or customer experience.',
                'definition_fr' => 'Un processus de collecte des retours utilisateurs, d\'analyse et d\'application des insights pour améliorer le produit ou l\'expérience client.',
                'letter' => 'F',
                'order' => 6,
            ],

            // Letter G
            [
                'term_en' => 'Gamification',
                'term_fr' => 'Ludification',
                'definition_en' => 'The use of game-like elements (such as badges, points, or progress bars) in software to increase user engagement and motivation.',
                'definition_fr' => 'L\'utilisation d\'éléments de jeu (comme des badges, points ou barres de progression) dans un logiciel pour augmenter l\'engagement et la motivation des utilisateurs.',
                'letter' => 'G',
                'order' => 1,
            ],
            [
                'term_en' => 'Go-to-Market (GTM) Strategy',
                'term_fr' => 'Stratégie de mise sur le marché (GTM)',
                'definition_en' => 'A plan that outlines how a company will introduce a product to the market, reach target customers, and achieve competitive advantage.',
                'definition_fr' => 'Un plan décrivant comment une entreprise introduira un produit sur le marché, atteindra les clients cibles et obtiendra un avantage concurrentiel.',
                'letter' => 'G',
                'order' => 2,
            ],

            // Letter H
            [
                'term_en' => 'Headless CMS',
                'term_fr' => 'CMS headless',
                'definition_en' => 'A content management system that separates the backend (content repository) from the frontend (presentation layer), enabling flexible content delivery.',
                'definition_fr' => 'Un système de gestion de contenu qui sépare le backend (référentiel de contenu) du frontend (couche de présentation), permettant une diffusion de contenu flexible.',
                'letter' => 'H',
                'order' => 1,
            ],
            [
                'term_en' => 'Help desk Software',
                'term_fr' => 'Logiciel de support client',
                'definition_en' => 'Tools that manage customer support requests, tickets, and communication channels efficiently.',
                'definition_fr' => 'Outils qui gèrent efficacement les demandes de support client, les tickets et les canaux de communication.',
                'letter' => 'H',
                'order' => 2,
            ],

            // Letter I
            [
                'term_en' => 'Ideation',
                'term_fr' => 'Idéation',
                'definition_en' => 'The creative process of generating, developing, and refining new ideas for products, features, or improvements.',
                'definition_fr' => 'Le processus créatif de génération, développement et raffinement de nouvelles idées pour des produits, fonctionnalités ou améliorations.',
                'letter' => 'I',
                'order' => 1,
            ],
            [
                'term_en' => 'Infrastructure as a Service (IaaS)',
                'term_fr' => 'Infrastructure en tant que Service (IaaS)',
                'definition_en' => 'A cloud computing model that provides virtualized computing resources like servers, storage, and networking on demand.',
                'definition_fr' => 'Un modèle d\'informatique en nuage qui fournit des ressources informatiques virtualisées comme des serveurs, du stockage et des réseaux à la demande.',
                'letter' => 'I',
                'order' => 2,
            ],

            // Letter J
            [
                'term_en' => 'JavaScript',
                'term_fr' => 'JavaScript',
                'definition_en' => 'A core programming language used to build dynamic and interactive web applications, essential for modern SaaS interfaces.',
                'definition_fr' => 'Un langage de programmation principal utilisé pour construire des applications web dynamiques et interactives, essentiel pour les interfaces SaaS modernes.',
                'letter' => 'J',
                'order' => 1,
            ],
            [
                'term_en' => 'Journey mapping',
                'term_fr' => 'Cartographie du parcours',
                'definition_en' => 'A visual representation of the steps users take when interacting with a product, used to identify pain points and opportunities for improvement.',
                'definition_fr' => 'Une représentation visuelle des étapes que suivent les utilisateurs lors de l\'interaction avec un produit, utilisée pour identifier les points de friction et les opportunités d\'amélioration.',
                'letter' => 'J',
                'order' => 2,
            ],

            // Letter K
            [
                'term_en' => 'KPI (Key Performance Indicator)',
                'term_fr' => 'KPI (Indicateur clé de performance)',
                'definition_en' => 'A measurable value that shows how effectively a company or team is achieving its business objectives.',
                'definition_fr' => 'Une valeur mesurable qui montre l\'efficacité avec laquelle une entreprise ou une équipe atteint ses objectifs commerciaux.',
                'letter' => 'K',
                'order' => 1,
            ],
            [
                'term_en' => 'Kanban',
                'term_fr' => 'Kanban',
                'definition_en' => 'An agile project management method that visualizes work on a board to improve flow, efficiency, and task prioritization.',
                'definition_fr' => 'Une méthode de gestion de projet agile qui visualise le travail sur un tableau pour améliorer le flux, l\'efficacité et la priorisation des tâches.',
                'letter' => 'K',
                'order' => 2,
            ],
            [
                'term_en' => 'Knowledge base',
                'term_fr' => 'Base de connaissances',
                'definition_en' => 'A centralized collection of articles, guides, and FAQs designed to help users find answers and learn independently.',
                'definition_fr' => 'Une collection centralisée d\'articles, de guides et de FAQ conçue pour aider les utilisateurs à trouver des réponses et à apprendre de manière autonome.',
                'letter' => 'K',
                'order' => 3,
            ],
            [
                'term_en' => 'Kubernetes',
                'term_fr' => 'Kubernetes',
                'definition_en' => 'An open-source system for automating the deployment, scaling, and management of containerized applications.',
                'definition_fr' => 'Un système open-source pour automatiser le déploiement, la mise à l\'échelle et la gestion d\'applications conteneurisées.',
                'letter' => 'K',
                'order' => 4,
            ],

            // Letter L
            [
                'term_en' => 'Landing page',
                'term_fr' => 'Page d\'atterrissage',
                'definition_en' => 'A standalone webpage designed to convert visitors into leads or customers through focused messaging and a clear call-to-action.',
                'definition_fr' => 'Une page web autonome conçue pour convertir les visiteurs en prospects ou clients grâce à un message ciblé et un appel à l\'action clair.',
                'letter' => 'L',
                'order' => 1,
            ],
            [
                'term_en' => 'Lean Startup',
                'term_fr' => 'Lean Startup',
                'definition_en' => 'A methodology focused on building products quickly, testing hypotheses, and learning from user feedback to reduce waste.',
                'definition_fr' => 'Une méthodologie axée sur la construction rapide de produits, le test d\'hypothèses et l\'apprentissage à partir des retours utilisateurs pour réduire le gaspillage.',
                'letter' => 'L',
                'order' => 2,
            ],
            [
                'term_en' => 'Lifetime Value (LTV)',
                'term_fr' => 'Valeur vie client (LTV)',
                'definition_en' => 'The total revenue a business can expect from a single customer throughout their relationship with the company.',
                'definition_fr' => 'Le revenu total qu\'une entreprise peut attendre d\'un seul client tout au long de sa relation avec l\'entreprise.',
                'letter' => 'L',
                'order' => 3,
            ],
            [
                'term_en' => 'Low-Code Platform',
                'term_fr' => 'Plateforme low-code',
                'definition_en' => 'A development environment that enables users to create software with minimal manual coding through drag-and-drop tools and visual interfaces.',
                'definition_fr' => 'Un environnement de développement permettant aux utilisateurs de créer des logiciels avec un minimum de codage manuel grâce à des outils glisser-déposer et des interfaces visuelles.',
                'letter' => 'L',
                'order' => 4,
            ],
            [
                'term_en' => 'Load Balancing',
                'term_fr' => 'Répartition de charge',
                'definition_en' => 'A method of distributing network or application traffic across multiple servers to improve speed, reliability, and uptime.',
                'definition_fr' => 'Une méthode de distribution du trafic réseau ou applicatif sur plusieurs serveurs pour améliorer la vitesse, la fiabilité et la disponibilité.',
                'letter' => 'L',
                'order' => 5,
            ],

            // Letter M
            [
                'term_en' => 'Machine Learning (ML)',
                'term_fr' => 'Apprentissage automatique (ML)',
                'definition_en' => 'A subset of artificial intelligence that enables systems to learn and improve from data without being explicitly programmed.',
                'definition_fr' => 'Un sous-ensemble de l\'intelligence artificielle qui permet aux systèmes d\'apprendre et de s\'améliorer à partir de données sans être explicitement programmés.',
                'letter' => 'M',
                'order' => 1,
            ],
            [
                'term_en' => 'Managed hosting',
                'term_fr' => 'Hébergement géré',
                'definition_en' => 'A hosting service where the provider handles setup, maintenance, security, and performance optimization on behalf of the user.',
                'definition_fr' => 'Un service d\'hébergement où le fournisseur gère la configuration, la maintenance, la sécurité et l\'optimisation des performances pour le compte de l\'utilisateur.',
                'letter' => 'M',
                'order' => 2,
            ],
            [
                'term_en' => 'Market fit (Product-Market Fit)',
                'term_fr' => 'Adéquation produit-marché',
                'definition_en' => 'The stage where a product successfully meets the needs and demands of its target audience, resulting in strong user growth and retention.',
                'definition_fr' => 'L\'étape où un produit répond avec succès aux besoins et aux demandes de son public cible, entraînant une forte croissance et fidélisation des utilisateurs.',
                'letter' => 'M',
                'order' => 3,
            ],
            [
                'term_en' => 'Marketing automation',
                'term_fr' => 'Automatisation marketing',
                'definition_en' => 'Software that automates repetitive marketing tasks such as email campaigns, lead nurturing, and social media management.',
                'definition_fr' => 'Logiciel qui automatise les tâches marketing répétitives comme les campagnes email, la nurturing de leads et la gestion des réseaux sociaux.',
                'letter' => 'M',
                'order' => 4,
            ],
            [
                'term_en' => 'Metrics dashboard',
                'term_fr' => 'Tableau de bord des métriques',
                'definition_en' => 'A visual overview of key performance indicators (KPIs) and analytics used to track progress and business health.',
                'definition_fr' => 'Une vue d\'ensemble visuelle des indicateurs clés de performance (KPI) et des analyses utilisées pour suivre la progression et la santé de l\'entreprise.',
                'letter' => 'M',
                'order' => 5,
            ],
            [
                'term_en' => 'Microservices',
                'term_fr' => 'Microservices',
                'definition_en' => 'An architectural approach where software is built as a collection of small, independent services that communicate through APIs.',
                'definition_fr' => 'Une approche architecturale où le logiciel est construit comme une collection de petits services indépendants qui communiquent via des API.',
                'letter' => 'M',
                'order' => 6,
            ],
            [
                'term_en' => 'Minimum viable product (MVP)',
                'term_fr' => 'Produit minimum viable (MVP)',
                'definition_en' => 'The simplest version of a product that allows teams to test core assumptions and gather feedback from early users.',
                'definition_fr' => 'La version la plus simple d\'un produit permettant aux équipes de tester les hypothèses fondamentales et de recueillir les retours des premiers utilisateurs.',
                'letter' => 'M',
                'order' => 7,
            ],
            [
                'term_en' => 'Mobile optimization',
                'term_fr' => 'Optimisation mobile',
                'definition_en' => 'The process of designing and adjusting websites or applications to deliver a seamless experience on mobile devices.',
                'definition_fr' => 'Le processus de conception et d\'ajustement des sites web ou applications pour offrir une expérience fluide sur les appareils mobiles.',
                'letter' => 'M',
                'order' => 8,
            ],
            [
                'term_en' => 'Monthly recurring revenue (MRR)',
                'term_fr' => 'Revenu mensuel récurrent (MRR)',
                'definition_en' => 'A key SaaS metric that represents predictable monthly income from active subscriptions.',
                'definition_fr' => 'Une métrique SaaS clé représentant le revenu mensuel prévisible provenant des abonnements actifs.',
                'letter' => 'M',
                'order' => 9,
            ],

            // Letter N
            [
                'term_en' => 'Net promoter score (NPS)',
                'term_fr' => 'Score Net Promoter (NPS)',
                'definition_en' => 'A customer satisfaction metric that measures how likely users are to recommend a product or service to others.',
                'definition_fr' => 'Une métrique de satisfaction client qui mesure la probabilité que les utilisateurs recommandent un produit ou service à d\'autres.',
                'letter' => 'N',
                'order' => 1,
            ],
            [
                'term_en' => 'No-code platform',
                'term_fr' => 'Plateforme no-code',
                'definition_en' => 'A development environment that allows users to build apps and workflows without writing code, using visual interfaces instead.',
                'definition_fr' => 'Un environnement de développement permettant aux utilisateurs de créer des applications et des workflows sans écrire de code, en utilisant des interfaces visuelles.',
                'letter' => 'N',
                'order' => 2,
            ],
            [
                'term_en' => 'Notification system',
                'term_fr' => 'Système de notifications',
                'definition_en' => 'A feature that sends alerts or updates to users about important events, changes, or actions within a product.',
                'definition_fr' => 'Une fonctionnalité qui envoie des alertes ou des mises à jour aux utilisateurs concernant les événements importants, changements ou actions dans un produit.',
                'letter' => 'N',
                'order' => 3,
            ],
            [
                'term_en' => 'Niche market',
                'term_fr' => 'Marché de niche',
                'definition_en' => 'A focused segment of a broader market with specific needs that a product or service is designed to serve.',
                'definition_fr' => 'Un segment ciblé d\'un marché plus large avec des besoins spécifiques qu\'un produit ou service est conçu pour satisfaire.',
                'letter' => 'N',
                'order' => 4,
            ],

            // Letter O
            [
                'term_en' => 'Onboarding flow',
                'term_fr' => 'Parcours d\'intégration',
                'definition_en' => 'A step-by-step process designed to help new users get started and experience the product\'s core value quickly.',
                'definition_fr' => 'Un processus étape par étape conçu pour aider les nouveaux utilisateurs à démarrer et à découvrir rapidement la valeur fondamentale du produit.',
                'letter' => 'O',
                'order' => 1,
            ],
            [
                'term_en' => 'Open source',
                'term_fr' => 'Open source',
                'definition_en' => 'Software whose source code is publicly available for modification, enhancement, and distribution.',
                'definition_fr' => 'Logiciel dont le code source est publiquement disponible pour modification, amélioration et distribution.',
                'letter' => 'O',
                'order' => 2,
            ],
            [
                'term_en' => 'Opt-In',
                'term_fr' => 'Consentement explicite',
                'definition_en' => 'A user\'s consent to receive communication, notifications, or marketing materials, typically via email or in-app prompts.',
                'definition_fr' => 'Le consentement d\'un utilisateur à recevoir des communications, notifications ou supports marketing, généralement via email ou invites in-app.',
                'letter' => 'O',
                'order' => 3,
            ],
            [
                'term_en' => 'Outbound marketing',
                'term_fr' => 'Marketing sortant',
                'definition_en' => 'Marketing efforts that actively reach out to potential customers through channels like ads, cold emails, or events.',
                'definition_fr' => 'Efforts marketing qui atteignent activement les clients potentiels via des canaux comme les publicités, emails à froid ou événements.',
                'letter' => 'O',
                'order' => 4,
            ],
            [
                'term_en' => 'Optimization',
                'term_fr' => 'Optimisation',
                'definition_en' => 'The practice of improving a system, design, or process for better performance, speed, or conversion.',
                'definition_fr' => 'La pratique d\'amélioration d\'un système, design ou processus pour de meilleures performances, vitesse ou conversion.',
                'letter' => 'O',
                'order' => 5,
            ],

            // Letter P
            [
                'term_en' => 'Paywall',
                'term_fr' => 'Mur payant',
                'definition_en' => 'A system that restricts access to content or features until the user pays or subscribes.',
                'definition_fr' => 'Un système qui restreint l\'accès au contenu ou aux fonctionnalités jusqu\'à ce que l\'utilisateur paie ou s\'abonne.',
                'letter' => 'P',
                'order' => 1,
            ],
            [
                'term_en' => 'Persona (User persona)',
                'term_fr' => 'Persona (Persona utilisateur)',
                'definition_en' => 'A fictional profile representing a key segment of your audience, used to guide product design and marketing strategies.',
                'definition_fr' => 'Un profil fictif représentant un segment clé de votre audience, utilisé pour guider la conception du produit et les stratégies marketing.',
                'letter' => 'P',
                'order' => 2,
            ],
            [
                'term_en' => 'Pipeline',
                'term_fr' => 'Pipeline',
                'definition_en' => 'A structured process of stages that leads prospects from initial contact to conversion, often used in sales and development contexts.',
                'definition_fr' => 'Un processus structuré d\'étapes qui mène les prospects du contact initial à la conversion, souvent utilisé dans les contextes de vente et de développement.',
                'letter' => 'P',
                'order' => 3,
            ],
            [
                'term_en' => 'Plugin',
                'term_fr' => 'Extension',
                'definition_en' => 'A piece of software that adds specific functionality to an existing application or platform.',
                'definition_fr' => 'Un logiciel qui ajoute des fonctionnalités spécifiques à une application ou plateforme existante.',
                'letter' => 'P',
                'order' => 4,
            ],
            [
                'term_en' => 'Prototype',
                'term_fr' => 'Prototype',
                'definition_en' => 'An early, simplified version of a product used to test concepts and gather feedback before full development.',
                'definition_fr' => 'Une version préliminaire et simplifiée d\'un produit utilisée pour tester des concepts et recueillir des retours avant le développement complet.',
                'letter' => 'P',
                'order' => 5,
            ],
            [
                'term_en' => 'Product-Led growth (PLG)',
                'term_fr' => 'Croissance axée sur le produit (PLG)',
                'definition_en' => 'A go-to-market strategy where the product itself drives user acquisition, conversion, and expansion.',
                'definition_fr' => 'Une stratégie de mise sur le marché où le produit lui-même génère l\'acquisition d\'utilisateurs, la conversion et l\'expansion.',
                'letter' => 'P',
                'order' => 6,
            ],

            // Letter Q
            [
                'term_en' => 'Quality assurance (QA)',
                'term_fr' => 'Assurance qualité (QA)',
                'definition_en' => 'The process of systematically testing software to ensure it meets quality standards and is free from defects.',
                'definition_fr' => 'Le processus de test systématique d\'un logiciel pour s\'assurer qu\'il respecte les normes de qualité et est exempt de défauts.',
                'letter' => 'Q',
                'order' => 1,
            ],
            [
                'term_en' => 'Query',
                'term_fr' => 'Requête',
                'definition_en' => 'A request made to a database to retrieve or manipulate specific information.',
                'definition_fr' => 'Une demande faite à une base de données pour récupérer ou manipuler des informations spécifiques.',
                'letter' => 'Q',
                'order' => 2,
            ],
            [
                'term_en' => 'Quota',
                'term_fr' => 'Quota',
                'definition_en' => 'A set limit or target for performance, usage, or sales within a defined period.',
                'definition_fr' => 'Une limite ou un objectif fixé pour la performance, l\'utilisation ou les ventes dans une période définie.',
                'letter' => 'Q',
                'order' => 3,
            ],

            // Letter R
            [
                'term_en' => 'REST API',
                'term_fr' => 'API REST',
                'definition_en' => 'Representational State Transfer API, a web service architecture that uses standard HTTP methods to enable communication between systems.',
                'definition_fr' => 'API REST (Representational State Transfer), une architecture de service web utilisant les méthodes HTTP standard pour permettre la communication entre systèmes.',
                'letter' => 'R',
                'order' => 1,
            ],
            [
                'term_en' => 'Refactoring',
                'term_fr' => 'Refactoring',
                'definition_en' => 'The process of restructuring existing code to improve readability, maintainability, and performance without changing its functionality.',
                'definition_fr' => 'Le processus de restructuration du code existant pour améliorer la lisibilité, la maintenabilité et les performances sans changer sa fonctionnalité.',
                'letter' => 'R',
                'order' => 2,
            ],
            [
                'term_en' => 'Rate limiting',
                'term_fr' => 'Limitation de débit',
                'definition_en' => 'A technique that controls the number of requests a user or application can make within a specific time period to prevent abuse and ensure system stability.',
                'definition_fr' => 'Une technique qui contrôle le nombre de requêtes qu\'un utilisateur ou une application peut effectuer dans une période donnée pour prévenir les abus et assurer la stabilité du système.',
                'letter' => 'R',
                'order' => 3,
            ],
            [
                'term_en' => 'Real-time processing',
                'term_fr' => 'Traitement en temps réel',
                'definition_en' => 'The ability to process data and deliver results immediately as events occur, enabling instant updates and interactions.',
                'definition_fr' => 'La capacité de traiter les données et de fournir des résultats immédiatement à mesure que les événements se produisent, permettant des mises à jour et interactions instantanées.',
                'letter' => 'R',
                'order' => 4,
            ],
            [
                'term_en' => 'Recurring revenue',
                'term_fr' => 'Revenu récurrent',
                'definition_en' => 'Predictable income generated from subscription-based services, providing financial stability and growth predictability for SaaS businesses.',
                'definition_fr' => 'Revenu prévisible généré par les services par abonnement, offrant stabilité financière et prévisibilité de croissance pour les entreprises SaaS.',
                'letter' => 'R',
                'order' => 5,
            ],
            [
                'term_en' => 'Regression testing',
                'term_fr' => 'Test de régression',
                'definition_en' => 'Testing performed to ensure that new changes or updates don\'t break existing functionality in previously working features.',
                'definition_fr' => 'Tests effectués pour s\'assurer que les nouveaux changements ou mises à jour ne cassent pas les fonctionnalités existantes des fonctionnalités précédemment fonctionnelles.',
                'letter' => 'R',
                'order' => 6,
            ],
            [
                'term_en' => 'Repository',
                'term_fr' => 'Dépôt',
                'definition_en' => 'A storage location where code, data, or project files are kept and version-controlled, typically using systems like Git.',
                'definition_fr' => 'Un emplacement de stockage où le code, les données ou les fichiers de projet sont conservés et versionnés, généralement en utilisant des systèmes comme Git.',
                'letter' => 'R',
                'order' => 7,
            ],

            // Letter S
            [
                'term_en' => 'Retention rate',
                'term_fr' => 'Taux de rétention',
                'definition_en' => 'The percentage of customers who continue using a product over a specific period, indicating satisfaction and loyalty.',
                'definition_fr' => 'Le pourcentage de clients qui continuent à utiliser un produit sur une période spécifique, indiquant la satisfaction et la fidélité.',
                'letter' => 'S',
                'order' => 1,
            ],
            [
                'term_en' => 'Roadmap',
                'term_fr' => 'Feuille de route',
                'definition_en' => 'A visual plan outlining upcoming product features, improvements, and long-term goals.',
                'definition_fr' => 'Un plan visuel décrivant les fonctionnalités à venir du produit, les améliorations et les objectifs à long terme.',
                'letter' => 'S',
                'order' => 2,
            ],
            [
                'term_en' => 'ROI (Return on Investment)',
                'term_fr' => 'ROI (Retour sur investissement)',
                'definition_en' => 'A metric that measures the profitability or effectiveness of an investment relative to its cost.',
                'definition_fr' => 'Une métrique qui mesure la rentabilité ou l\'efficacité d\'un investissement par rapport à son coût.',
                'letter' => 'S',
                'order' => 3,
            ],
            [
                'term_en' => 'Release Notes',
                'term_fr' => 'Notes de version',
                'definition_en' => 'Documentation detailing new features, bug fixes, or updates included in a product release.',
                'definition_fr' => 'Documentation détaillant les nouvelles fonctionnalités, corrections de bugs ou mises à jour incluses dans une version de produit.',
                'letter' => 'S',
                'order' => 4,
            ],
            [
                'term_en' => 'Responsive design',
                'term_fr' => 'Design adaptatif',
                'definition_en' => 'A design approach that ensures websites and applications automatically adjust to different screen sizes and devices.',
                'definition_fr' => 'Une approche de design qui garantit que les sites web et applications s\'ajustent automatiquement aux différentes tailles d\'écran et appareils.',
                'letter' => 'S',
                'order' => 5,
            ],

            // Letter T
            [
                'term_en' => 'TAM',
                'term_fr' => 'TAM (Marché total adressable)',
                'definition_en' => 'The total revenue opportunity available for a product or service if 100% market share is achieved.',
                'definition_fr' => 'L\'opportunité de revenus totale disponible pour un produit ou service si 100% de part de marché est atteinte.',
                'letter' => 'T',
                'order' => 1,
            ],
            [
                'term_en' => 'Tech stack',
                'term_fr' => 'Stack technique',
                'definition_en' => 'The combination of software technologies and tools a company uses to build and run its applications.',
                'definition_fr' => 'La combinaison de technologies logicielles et d\'outils qu\'une entreprise utilise pour construire et exécuter ses applications.',
                'letter' => 'T',
                'order' => 2,
            ],
            [
                'term_en' => 'Trial conversion rate',
                'term_fr' => 'Taux de conversion d\'essai',
                'definition_en' => 'The percentage of users who convert from a free trial to a paid subscription.',
                'definition_fr' => 'Le pourcentage d\'utilisateurs qui passent d\'un essai gratuit à un abonnement payant.',
                'letter' => 'T',
                'order' => 3,
            ],
            [
                'term_en' => 'Telemetry',
                'term_fr' => 'Télémétrie',
                'definition_en' => 'Data collected from software usage to monitor performance and user behavior.',
                'definition_fr' => 'Données collectées à partir de l\'utilisation du logiciel pour surveiller les performances et le comportement des utilisateurs.',
                'letter' => 'T',
                'order' => 4,
            ],

            // Letter U
            [
                'term_en' => 'Uptime',
                'term_fr' => 'Temps de disponibilité',
                'definition_en' => 'The percentage of time a service or application is operational and available to users.',
                'definition_fr' => 'Le pourcentage de temps pendant lequel un service ou une application est opérationnel et disponible pour les utilisateurs.',
                'letter' => 'U',
                'order' => 1,
            ],
            [
                'term_en' => 'User journey',
                'term_fr' => 'Parcours utilisateur',
                'definition_en' => 'The path a user takes from first interaction with a product to achieving their goal.',
                'definition_fr' => 'Le chemin qu\'un utilisateur emprunte depuis sa première interaction avec un produit jusqu\'à l\'atteinte de son objectif.',
                'letter' => 'U',
                'order' => 2,
            ],
            [
                'term_en' => 'Usage-based pricing',
                'term_fr' => 'Tarification à l\'usage',
                'definition_en' => 'A pricing model where customers pay based on the amount they use a service.',
                'definition_fr' => 'Un modèle de tarification où les clients paient en fonction de la quantité de service qu\'ils utilisent.',
                'letter' => 'U',
                'order' => 3,
            ],
            [
                'term_en' => 'UX (User experience)',
                'term_fr' => 'UX (Expérience utilisateur)',
                'definition_en' => 'The overall experience and satisfaction a user has while interacting with a product.',
                'definition_fr' => 'L\'expérience globale et la satisfaction qu\'un utilisateur ressent lors de son interaction avec un produit.',
                'letter' => 'U',
                'order' => 4,
            ],

            // Letter V
            [
                'term_en' => 'Viral coefficient',
                'term_fr' => 'Coefficient viral',
                'definition_en' => 'A metric that measures how many new users each existing user generates through referrals.',
                'definition_fr' => 'Une métrique qui mesure combien de nouveaux utilisateurs chaque utilisateur existant génère par le parrainage.',
                'letter' => 'V',
                'order' => 1,
            ],
            [
                'term_en' => 'Venture capital (VC)',
                'term_fr' => 'Capital-risque (VC)',
                'definition_en' => 'Funding provided by investors to startups with high growth potential in exchange for equity.',
                'definition_fr' => 'Financement fourni par des investisseurs aux startups à fort potentiel de croissance en échange de parts de capital.',
                'letter' => 'V',
                'order' => 2,
            ],

            // Letter W
            [
                'term_en' => 'Webhooks',
                'term_fr' => 'Webhooks',
                'definition_en' => 'Automated messages sent from an app when a specific event occurs, enabling integrations between software.',
                'definition_fr' => 'Messages automatisés envoyés depuis une application lorsqu\'un événement spécifique se produit, permettant l\'intégration entre logiciels.',
                'letter' => 'W',
                'order' => 1,
            ],
            [
                'term_en' => 'Workflow automation',
                'term_fr' => 'Automatisation des flux de travail',
                'definition_en' => 'The use of software to automate repetitive tasks and processes within an organization.',
                'definition_fr' => 'L\'utilisation de logiciels pour automatiser les tâches et processus répétitifs au sein d\'une organisation.',
                'letter' => 'W',
                'order' => 2,
            ],
            [
                'term_en' => 'White-label SaaS',
                'term_fr' => 'SaaS en marque blanche',
                'definition_en' => 'A SaaS product that can be rebranded and sold by another company as its own.',
                'definition_fr' => 'Un produit SaaS qui peut être rebrandé et vendu par une autre entreprise sous sa propre marque.',
                'letter' => 'W',
                'order' => 3,
            ],

            // Letter X
            [
                'term_en' => 'XaaS (Anything-as-a-service)',
                'term_fr' => 'XaaS (Tout-en-tant-que-service)',
                'definition_en' => 'An umbrella term for services delivered over the cloud, including SaaS, PaaS, and IaaS.',
                'definition_fr' => 'Un terme générique pour les services fournis via le cloud, incluant SaaS, PaaS et IaaS.',
                'letter' => 'X',
                'order' => 1,
            ],
            [
                'term_en' => 'XML (Extensible markup language)',
                'term_fr' => 'XML (Langage de balisage extensible)',
                'definition_en' => 'A format for structuring and exchanging data between systems.',
                'definition_fr' => 'Un format de structuration et d\'échange de données entre systèmes.',
                'letter' => 'X',
                'order' => 2,
            ],

            // Letter Y
            [
                'term_en' => 'Yield',
                'term_fr' => 'Rendement',
                'definition_en' => 'The return or revenue generated by a product, feature, or marketing channel.',
                'definition_fr' => 'Le retour ou le revenu généré par un produit, une fonctionnalité ou un canal marketing.',
                'letter' => 'Y',
                'order' => 1,
            ],
            [
                'term_en' => 'Year-over-year (YoY)',
                'term_fr' => 'Année sur année (YoY)',
                'definition_en' => 'A growth metric comparing performance for the same period in consecutive years.',
                'definition_fr' => 'Une métrique de croissance comparant les performances pour la même période sur des années consécutives.',
                'letter' => 'Y',
                'order' => 2,
            ],
            [
                'term_en' => 'Young company metrics',
                'term_fr' => 'Métriques de jeune entreprise',
                'definition_en' => 'KPIs used to measure growth and traction in early-stage startups.',
                'definition_fr' => 'KPI utilisés pour mesurer la croissance et la traction des startups en phase de démarrage.',
                'letter' => 'Y',
                'order' => 3,
            ],

            // Letter Z
            [
                'term_en' => 'Zero downtime deployment',
                'term_fr' => 'Déploiement sans interruption',
                'definition_en' => 'Deploying software updates without disrupting service availability for users.',
                'definition_fr' => 'Déployer des mises à jour logicielles sans interrompre la disponibilité du service pour les utilisateurs.',
                'letter' => 'Z',
                'order' => 1,
            ],
            [
                'term_en' => 'Zapier Integration',
                'term_fr' => 'Intégration Zapier',
                'definition_en' => 'Connecting apps and automating workflows using the Zapier platform.',
                'definition_fr' => 'Connecter des applications et automatiser des flux de travail en utilisant la plateforme Zapier.',
                'letter' => 'Z',
                'order' => 2,
            ],
        ];

        foreach ($glossaries as $glossary) {
            Glossary::create($glossary);
        }
    }
}
